/**
 * Multi-Level Achievement System
 * 5 Levels with 15 Achievements Each (75 Total)
 * Progressive difficulty scaling
 */

const Achievement = require('../models/Achievement');
const User = require('../models/User');

// LEVEL 1: BEGINNER (15 Achievements) - Easy targets
const LEVEL_1_ACHIEVEMENTS = {
    // Documents (3)
    FIRST_UPLOAD: {
        id: 'l1_first_upload',
        title: '📄 First Upload',
        description: 'Upload your very first document',
        icon: '📄',
        category: 'document',
        level: 1,
        target: 1,
        xpReward: 50,
        check: (user) => user.stats.totalDocuments >= 1,
    },
    DOC_STARTER: {
        id: 'l1_doc_starter',
        title: '📚 Doc Starter',
        description: 'Upload 3 documents',
        icon: '📚',
        category: 'document',
        level: 1,
        target: 3,
        xpReward: 100,
        check: (user) => user.stats.totalDocuments >= 3,
    },
    KNOWLEDGE_SEEKER: {
        id: 'l1_knowledge_seeker',
        title: '🔍 Knowledge Seeker',
        description: 'Upload 5 different types of documents',
        icon: '🔍',
        category: 'document',
        level: 1,
        target: 5,
        xpReward: 150,
        check: (user) => user.stats.totalDocuments >= 5,
    },

    // Quizzes (3)
    QUIZ_BEGINNER: {
        id: 'l1_quiz_beginner',
        title: '🧠 Quiz Beginner',
        description: 'Complete your first quiz',
        icon: '🧠',
        category: 'quiz',
        level: 1,
        target: 1,
        xpReward: 50,
        check: (user) => user.stats.totalQuizzes >= 1,
    },
    QUIZ_EXPLORER: {
        id: 'l1_quiz_explorer',
        title: '🎯 Quiz Explorer',
        description: 'Complete 3 quizzes',
        icon: '🎯',
        category: 'quiz',
        level: 1,
        target: 3,
        xpReward: 100,
        check: (user) => user.stats.totalQuizzes >= 3,
    },
    QUIZ_ENTHUSIAST: {
        id: 'l1_quiz_enthusiast',
        title: '💡 Quiz Enthusiast',
        description: 'Complete 5 quizzes',
        icon: '💡',
        category: 'quiz',
        level: 1,
        target: 5,
        xpReward: 150,
        check: (user) => user.stats.totalQuizzes >= 5,
    },

    // Flashcards (3)
    CARD_CREATOR: {
        id: 'l1_card_creator',
        title: '⚡ Card Creator',
        description: 'Create your first flashcard',
        icon: '⚡',
        category: 'flashcard',
        level: 1,
        target: 1,
        xpReward: 50,
        check: (user) => user.stats.totalFlashcards >= 1,
    },
    CARD_COLLECTOR: {
        id: 'l1_card_collector',
        title: '🎴 Card Collector',
        description: 'Create 10 flashcards',
        icon: '🎴',
        category: 'flashcard',
        level: 1,
        target: 10,
        xpReward: 100,
        check: (user) => user.stats.totalFlashcards >= 10,
    },
    MEMORY_STARTER: {
        id: 'l1_memory_starter',
        title: '🧩 Memory Starter',
        description: 'Create 25 flashcards',
        icon: '🧩',
        category: 'flashcard',
        level: 1,
        target: 25,
        xpReward: 150,
        check: (user) => user.stats.totalFlashcards >= 25,
    },

    // Streaks (3)
    DAY_ONE: {
        id: 'l1_day_one',
        title: '🌟 Day One',
        description: 'Start your learning journey',
        icon: '🌟',
        category: 'streak',
        level: 1,
        target: 1,
        xpReward: 50,
        check: (user) => user.stats.studyStreak >= 1,
    },
    THREE_DAY_STREAK: {
        id: 'l1_three_day',
        title: '🔥 Three Day Streak',
        description: 'Maintain a 3-day study streak',
        icon: '🔥',
        category: 'streak',
        level: 1,
        target: 3,
        xpReward: 100,
        check: (user) => user.stats.studyStreak >= 3,
    },
    WEEK_BEGINNER: {
        id: 'l1_week_beginner',
        title: '⭐ Week Beginner',
        description: 'Study for 7 consecutive days',
        icon: '⭐',
        category: 'streak',
        level: 1,
        target: 7,
        xpReward: 200,
        check: (user) => user.stats.studyStreak >= 7,
    },

    // Mixed/Misc (3)
    LEVEL_2_READY: {
        id: 'l1_level_2',
        title: '🎓 Level 2 Ready',
        description: 'Reach user level 2',
        icon: '🎓',
        category: 'level',
        level: 1,
        target: 2,
        xpReward: 100,
        check: (user) => user.level.currentLevel >= 2,
    },
    EARLY_BIRD: {
        id: 'l1_early_bird',
        title: '🌅 Early Bird',
        description: 'Study within first week',
        icon: '🌅',
        category: 'consistency',
        level: 1,
        target: 1,
        xpReward: 75,
        check: (user) => true, // Auto-unlock for early users
    },
    FIRST_STEP: {
        id: 'l1_first_step',
        title: '👣 First Step',
        description: 'Complete any learning activity',
        icon: '👣',
        category: 'mastery',
        level: 1,
        target: 1,
        xpReward: 50,
        check: (user) => (user.stats.totalDocuments + user.stats.totalQuizzes + user.stats.totalFlashcards) >= 1,
    },
};

// LEVEL 2: INTERMEDIATE (15 Achievements) - Moderate targets
const LEVEL_2_ACHIEVEMENTS = {
    // Documents (3)
    DOC_BUILDER: {
        id: 'l2_doc_builder',
        title: '📖 Doc Builder',
        description: 'Upload 10 documents',
        icon: '📖',
        category: 'document',
        level: 2,
        target: 10,
        xpReward: 200,
        check: (user) => user.stats.totalDocuments >= 10,
    },
    LIBRARY_STARTER: {
        id: 'l2_library_starter',
        title: '🏛️ Library Starter',
        description: 'Upload 15 documents',
        icon: '🏛️',
        category: 'document',
        level: 2,
        target: 15,
        xpReward: 300,
        check: (user) => user.stats.totalDocuments >= 15,
    },
    CONTENT_CURATOR: {
        id: 'l2_content_curator',
        title: '📚 Content Curator',
        description: 'Upload 20 high-quality documents',
        icon: '📚',
        category: 'document',
        level: 2,
        target: 20,
        xpReward: 400,
        check: (user) => user.stats.totalDocuments >= 20,
    },

    // Quizzes (3)
    QUIZ_APPRENTICE: {
        id: 'l2_quiz_apprentice',
        title: '🎮 Quiz Apprentice',
        description: 'Complete 10 quizzes',
        icon: '🎮',
        category: 'quiz',
        level: 2,
        target: 10,
        xpReward: 200,
        check: (user) => user.stats.totalQuizzes >= 10,
    },
    QUIZ_REGULAR: {
        id: 'l2_quiz_regular',
        title: '🎯 Quiz Regular',
        description: 'Complete 15 quizzes',
        icon: '🎯',
        category: 'quiz',
        level: 2,
        target: 15,
        xpReward: 300,
        check: (user) => user.stats.totalQuizzes >= 15,
    },
    TEST_TAKER: {
        id: 'l2_test_taker',
        title: '📝 Test Taker',
        description: 'Complete 20 quizzes',
        icon: '📝',
        category: 'quiz',
        level: 2,
        target: 20,
        xpReward: 400,
        check: (user) => user.stats.totalQuizzes >= 20,
    },

    // Flashcards (3)
    CARD_BUILDER: {
        id: 'l2_card_builder',
        title: '🎴 Card Builder',
        description: 'Create 50 flashcards',
        icon: '🎴',
        category: 'flashcard',
        level: 2,
        target: 50,
        xpReward: 200,
        check: (user) => user.stats.totalFlashcards >= 50,
    },
    MEMORY_TRAINER: {
        id: 'l2_memory_trainer',
        title: '🧠 Memory Trainer',
        description: 'Create 75 flashcards',
        icon: '🧠',
        category: 'flashcard',
        level: 2,
        target: 75,
        xpReward: 300,
        check: (user) => user.stats.totalFlashcards >= 75,
    },
    FLASH_MASTER: {
        id: 'l2_flash_master',
        title: '⚡ Flash Master',
        description: 'Create 100 flashcards',
        icon: '⚡',
        category: 'flashcard',
        level: 2,
        target: 100,
        xpReward: 400,
        check: (user) => user.stats.totalFlashcards >= 100,
    },

    // Streaks (3)
    TWO_WEEK_WARRIOR: {
        id: 'l2_two_week',
        title: '💪 Two Week Warrior',
        description: 'Maintain 14-day streak',
        icon: '💪',
        category: 'streak',
        level: 2,
        target: 14,
        xpReward: 300,
        check: (user) => user.stats.studyStreak >= 14,
    },
    MONTH_BEGINNER: {
        id: 'l2_month_beginner',
        title: '📅 Month Beginner',
        description: 'Study for 21 days straight',
        icon: '📅',
        category: 'streak',
        level: 2,
        target: 21,
        xpReward: 400,
        check: (user) => user.stats.studyStreak >= 21,
    },
    CONSISTENCY_BUILDER: {
        id: 'l2_consistency',
        title: '🎯 Consistency Builder',
        description: 'Maintain 30-day streak',
        icon: '🎯',
        category: 'streak',
        level: 2,
        target: 30,
        xpReward: 500,
        check: (user) => user.stats.studyStreak >= 30,
    },

    // Mixed/Misc (3)
    LEVEL_5_READY: {
        id: 'l2_level_5',
        title: '🚀 Level 5 Ready',
        description: 'Reach user level 5',
        icon: '🚀',
        category: 'level',
        level: 2,
        target: 5,
        xpReward: 300,
        check: (user) => user.level.currentLevel >= 5,
    },
    DEDICATED_LEARNER: {
        id: 'l2_dedicated',
        title: '💎 Dedicated Learner',
        description: 'Study regularly for 2 weeks',
        icon: '💎',
        category: 'consistency',
        level: 2,
        target: 14,
        xpReward: 250,
        check: (user) => user.stats.studyStreak >= 14,
    },
    PROGRESS_MAKER: {
        id: 'l2_progress',
        title: '📈 Progress Maker',
        description: 'Complete 30 total activities',
        icon: '📈',
        category: 'mastery',
        level: 2,
        target: 30,
        xpReward: 300,
        check: (user) => (user.stats.totalDocuments + user.stats.totalQuizzes + user.stats.totalFlashcards) >= 30,
    },
};

// LEVEL 3: ADVANCED (15 Achievements) - Hard targets  
const LEVEL_3_ACHIEVEMENTS = {
    // Documents (3)
    DOC_MASTER: {
        id: 'l3_doc_master',
        title: '📚 Doc Master',
        description: 'Upload 30 documents',
        icon: '📚',
        category: 'document',
        level: 3,
        target: 30,
        xpReward: 500,
        check: (user) => user.stats.totalDocuments >= 30,
    },
    LIBRARY_BUILDER: {
        id: 'l3_library_builder',
        title: '🏛️ Library Builder',
        description: 'Upload 40 documents',
        icon: '🏛️',
        category: 'document',
        level: 3,
        target: 40,
        xpReward: 600,
        check: (user) => user.stats.totalDocuments >= 40,
    },
    KNOWLEDGE_VAULT: {
        id: 'l3_knowledge_vault',
        title: '🗄️ Knowledge Vault',
        description: 'Upload 50 documents',
        icon: '🗄️',
        category: 'document',
        level: 3,
        target: 50,
        xpReward: 750,
        check: (user) => user.stats.totalDocuments >= 50,
    },

    // Quizzes (3)
    QUIZ_VETERAN: {
        id: 'l3_quiz_veteran',
        title: '🏆 Quiz Veteran',
        description: 'Complete 30 quizzes',
        icon: '🏆',
        category: 'quiz',
        level: 3,
        target: 30,
        xpReward: 500,
        check: (user) => user.stats.totalQuizzes >= 30,
    },
    QUIZ_EXPERT: {
        id: 'l3_quiz_expert',
        title: '🎓 Quiz Expert',
        description: 'Complete 40 quizzes',
        icon: '🎓',
        category: 'quiz',
        level: 3,
        target: 40,
        xpReward: 600,
        check: (user) => user.stats.totalQuizzes >= 40,
    },
    QUIZ_CHAMPION: {
        id: 'l3_quiz_champion',
        title: '👑 Quiz Champion',
        description: 'Complete 50 quizzes',
        icon: '👑',
        category: 'quiz',
        level: 3,
        target: 50,
        xpReward: 750,
        check: (user) => user.stats.totalQuizzes >= 50,
    },

    // Flashcards (3)
    CARD_EXPERT: {
        id: 'l3_card_expert',
        title: '🎴 Card Expert',
        description: 'Create 150 flashcards',
        icon: '🎴',
        category: 'flashcard',
        level: 3,
        target: 150,
        xpReward: 500,
        check: (user) => user.stats.totalFlashcards >= 150,
    },
    MEMORY_MASTER: {
        id: 'l3_memory_master',
        title: '🧠 Memory Master',
        description: 'Create 200 flashcards',
        icon: '🧠',
        category: 'flashcard',
        level: 3,
        target: 200,
        xpReward: 600,
        check: (user) => user.stats.totalFlashcards >= 200,
    },
    RECALL_CHAMPION: {
        id: 'l3_recall_champion',
        title: '⚡ Recall Champion',
        description: 'Create 250 flashcards',
        icon: '⚡',
        category: 'flashcard',
        level: 3,
        target: 250,
        xpReward: 750,
        check: (user) => user.stats.totalFlashcards >= 250,
    },

    // Streaks (3)
    MONTH_WARRIOR: {
        id: 'l3_month_warrior',
        title: '🔥 Month Warrior',
        description: 'Maintain 45-day streak',
        icon: '🔥',
        category: 'streak',
        level: 3,
        target: 45,
        xpReward: 600,
        check: (user) => user.stats.studyStreak >= 45,
    },
    TWO_MONTH_STREAK: {
        id: 'l3_two_month',
        title: '📅 Two Month Streak',
        description: 'Study for 60 days straight',
        icon: '📅',
        category: 'streak',
        level: 3,
        target: 60,
        xpReward: 750,
        check: (user) => user.stats.studyStreak >= 60,
    },
    PERSISTENCE_PRO: {
        id: 'l3_persistence',
        title: '💪 Persistence Pro',
        description: 'Maintain 75-day streak',
        icon: '💪',
        category: 'streak',
        level: 3,
        target: 75,
        xpReward: 900,
        check: (user) => user.stats.studyStreak >= 75,
    },

    // Mixed/Misc (3)
    LEVEL_10_READY: {
        id: 'l3_level_10',
        title: '🌟 Level 10 Ready',
        description: 'Reach user level 10',
        icon: '🌟',
        category: 'level',
        level: 3,
        target: 10,
        xpReward: 600,
        check: (user) => user.level.currentLevel >= 10,
    },
    ADVANCED_SCHOLAR: {
        id: 'l3_scholar',
        title: '🎓 Advanced Scholar',
        description: 'Complete 100 learning activities',
        icon: '🎓',
        category: 'mastery',
        level: 3,
        target: 100,
        xpReward: 700,
        check: (user) => (user.stats.totalDocuments + user.stats.totalQuizzes + user.stats.totalFlashcards) >= 100,
    },
    SPEED_LEARNER: {
        id: 'l3_speed',
        title: '⚡ Speed Learner',
        description: 'Complete activities quickly',
        icon: '⚡',
        category: 'speed',
        level: 3,
        target: 50,
        xpReward: 500,
        check: (user) => (user.stats.totalDocuments + user.stats.totalQuizzes + user.stats.totalFlashcards) >= 50,
    },
};

// Continue in next file due to size...

module.exports = {
    LEVEL_1_ACHIEVEMENTS,
    LEVEL_2_ACHIEVEMENTS,
    LEVEL_3_ACHIEVEMENTS,
};
