/**
 * Multi-Level Achievement System - Levels 4 & 5
 * 30 More Achievements (Expert & Legend tiers)
 */

// LEVEL 4: EXPERT (15 Achievements) - Very Hard targets
const LEVEL_4_ACHIEVEMENTS = {
    // Documents (3)
    ARCHIVE_MASTER: {
        id: 'l4_archive_master',
        title: '🗃️ Archive Master',
        description: 'Upload 75 documents',
        icon: '🗃️',
        category: 'document',
        level: 4,
        target: 75,
        xpReward: 1000,
        check: (user) => user.stats.totalDocuments >= 75,
    },
    KNOWLEDGE_EMPEROR: {
        id: 'l4_knowledge_emperor',
        title: '👑 Knowledge Emperor',
        description: 'Upload 100 documents',
        icon: '👑',
        category: 'document',
        level: 4,
        target: 100,
        xpReward: 1250,
        check: (user) => user.stats.totalDocuments >= 100,
    },
    LIBRARY_LEGEND: {
        id: 'l4_library_legend',
        title: '🏰 Library Legend',
        description: 'Upload 125 documents',
        icon: '🏰',
        category: 'document',
        level: 4,
        target: 125,
        xpReward: 1500,
        check: (user) => user.stats.totalDocuments >= 125,
    },

    // Quizzes (3)
    QUIZ_MASTER: {
        id: 'l4_quiz_master',
        title: '🏆 Quiz Master',
        description: 'Complete 75 quizzes',
        icon: '🏆',
        category: 'quiz',
        level: 4,
        target: 75,
        xpReward: 1000,
        check: (user) => user.stats.totalQuizzes >= 75,
    },
    TEST_GENIUS: {
        id: 'l4_test_genius',
        title: '🧠 Test Genius',
        description: 'Complete 100 quizzes',
        icon: '🧠',
        category: 'quiz',
        level: 4,
        target: 100,
        xpReward: 1250,
        check: (user) => user.stats.totalQuizzes >= 100,
    },
    QUIZ_LEGEND: {
        id: 'l4_quiz_legend',
        title: '⚡ Quiz Legend',
        description: 'Complete 125 quizzes',
        icon: '⚡',
        category: 'quiz',
        level: 4,
        target: 125,
        xpReward: 1500,
        check: (user) => user.stats.totalQuizzes >= 125,
    },

    // Flashcards (3)
    CARD_VIRTUOSO: {
        id: 'l4_card_virtuoso',
        title: '🎴 Card Virtuoso',
        description: 'Create 350 flashcards',
        icon: '🎴',
        category: 'flashcard',
        level: 4,
        target: 350,
        xpReward: 1000,
        check: (user) => user.stats.totalFlashcards >= 350,
    },
    MEMORY_LEGEND: {
        id: 'l4_memory_legend',
        title: '🧩 Memory Legend',
        description: 'Create 500 flashcards',
        icon: '🧩',
        category: 'flashcard',
        level: 4,
        target: 500,
        xpReward: 1250,
        check: (user) => user.stats.totalFlashcards >= 500,
    },
    RECALL_GOD: {
        id: 'l4_recall_god',
        title: '👑 Recall God',
        description: 'Create 650 flashcards',
        icon: '👑',
        category: 'flashcard',
        level: 4,
        target: 650,
        xpReward: 1500,
        check: (user) => user.stats.totalFlashcards >= 650,
    },

    // Streaks (3)
    HUNDRED_DAY_HERO: {
        id: 'l4_hundred_day',
        title: '💯 Hundred Day Hero',
        description: 'Maintain 100-day streak',
        icon: '💯',
        category: 'streak',
        level: 4,
        target: 100,
        xpReward: 1200,
        check: (user) => user.stats.studyStreak >= 100,
    },
    DEDICATION_MASTER: {
        id: 'l4_dedication_master',
        title: '🔥 Dedication Master',
        description: 'Study for 150 days straight',
        icon: '🔥',
        category: 'streak',
        level: 4,
        target: 150,
        xpReward: 1500,
        check: (user) => user.stats.studyStreak >= 150,
    },
    UNSTOPPABLE_FORCE: {
        id: 'l4_unstoppable',
        title: '⚡ Unstoppable Force',
        description: 'Maintain 180-day streak',
        icon: '⚡',
        category: 'streak',
        level: 4,
        target: 180,
        xpReward: 1800,
        check: (user) => user.stats.studyStreak >= 180,
    },

    // Mixed/Misc (3)
    LEVEL_15_MASTER: {
        id: 'l4_level_15',
        title: '💎 Level 15 Master',
        description: 'Reach user level 15',
        icon: '💎',
        category: 'level',
        level: 4,
        target: 15,
        xpReward: 1000,
        check: (user) => user.level.currentLevel >= 15,
    },
    ELITE_SCHOLAR: {
        id: 'l4_elite_scholar',
        title: '🎓 Elite Scholar',
        description: 'Complete 200 total activities',
        icon: '🎓',
        category: 'mastery',
        level: 4,
        target: 200,
        xpReward: 1200,
        check: (user) => (user.stats.totalDocuments + user.stats.totalQuizzes + user.stats.totalFlashcards) >= 200,
    },
    ACCURACY_ACE: {
        id: 'l4_accuracy',
        title: '🎯 Accuracy Ace',
        description: 'Maintain high quiz accuracy',
        icon: '🎯',
        category: 'accuracy',
        level: 4,
        target: 100,
        xpReward: 1000,
        check: (user) => user.stats.totalQuizzes >= 100,
    },
};

// LEVEL 5: LEGEND (15 Achievements) - Extreme/Legendary targets
const LEVEL_5_ACHIEVEMENTS = {
    // Documents (3)
    DOCUMENT_GOD: {
        id: 'l5_document_god',
        title: '🌟 Document God',
        description: 'Upload 200 documents',
        icon: '🌟',
        category: 'document',
        level: 5,
        target: 200,
        xpReward: 2000,
        check: (user) => user.stats.totalDocuments >= 200,
    },
    INFINITE_LIBRARY: {
        id: 'l5_infinite_library',
        title: '♾️ Infinite Library',
        description: 'Upload 300 documents',
        icon: '♾️',
        category: 'document',
        level: 5,
        target: 300,
        xpReward: 2500,
        check: (user) => user.stats.totalDocuments >= 300,
    },
    KNOWLEDGE_DEITY: {
        id: 'l5_knowledge_deity',
        title: '👑 Knowledge Deity',
        description: 'Upload 500 documents',
        icon: '👑',
        category: 'document',
        level: 5,
        target: 500,
        xpReward: 3000,
        check: (user) => user.stats.totalDocuments >= 500,
    },

    // Quizzes (3)
    QUIZ_IMMORTAL: {
        id: 'l5_quiz_immortal',
        title: '⚡ Quiz Immortal',
        description: 'Complete 200 quizzes',
        icon: '⚡',
        category: 'quiz',
        level: 5,
        target: 200,
        xpReward: 2000,
        check: (user) => user.stats.totalQuizzes >= 200,
    },
    ULTIMATE_TESTER: {
        id: 'l5_ultimate_tester',
        title: '🏆 Ultimate Tester',
        description: 'Complete 300 quizzes',
        icon: '🏆',
        category: 'quiz',
        level: 5,
        target: 300,
        xpReward: 2500,
        check: (user) => user.stats.totalQuizzes >= 300,
    },
    QUIZ_DEITY: {
        id: 'l5_quiz_deity',
        title: '👑 Quiz Deity',
        description: 'Complete 500 quizzes',
        icon: '👑',
        category: 'quiz',
        level: 5,
        target: 500,
        xpReward: 3000,
        check: (user) => user.stats.totalQuizzes >= 500,
    },

    // Flashcards (3)
    FLASHCARD_TITAN: {
        id: 'l5_card_titan',
        title: '⚡ Flashcard Titan',
        description: 'Create 1000 flashcards',
        icon: '⚡',
        category: 'flashcard',
        level: 5,
        target: 1000,
        xpReward: 2000,
        check: (user) => user.stats.totalFlashcards >= 1000,
    },
    MEMORY_IMMORTAL: {
        id: 'l5_memory_immortal',
        title: '🧠 Memory Immortal',
        description: 'Create 1500 flashcards',
        icon: '🧠',
        category: 'flashcard',
        level: 5,
        target: 1500,
        xpReward: 2500,
        check: (user) => user.stats.totalFlashcards >= 1500,
    },
    ULTIMATE_MEMORIZER: {
        id: 'l5_ultimate_memory',
        title: '👑 Ultimate Memorizer',
        description: 'Create 2000 flashcards',
        icon: '👑',
        category: 'flashcard',
        level: 5,
        target: 2000,
        xpReward: 3000,
        check: (user) => user.stats.totalFlashcards >= 2000,
    },

    // Streaks (3)
    YEAR_WARRIOR: {
        id: 'l5_year_warrior',
        title: '📅 Year Warrior',
        description: 'Maintain 250-day streak',
        icon: '📅',
        category: 'streak',
        level: 5,
        target: 250,
        xpReward: 2500,
        check: (user) => user.stats.studyStreak >= 250,
    },
    ETERNAL_STUDENT: {
        id: 'l5_eternal_student',
        title: '♾️ Eternal Student',
        description: 'Study for 365 days straight',
        icon: '♾️',
        category: 'streak',
        level: 5,
        target: 365,
        xpReward: 3000,
        check: (user) => user.stats.studyStreak >= 365,
    },
    LEGEND_STATUS: {
        id: 'l5_legend_status',
        title: '👑 Legend Status',
        description: 'Maintain 500-day streak',
        icon: '👑',
        category: 'streak',
        level: 5,
        target: 500,
        xpReward: 5000,
        check: (user) => user.stats.studyStreak >= 500,
    },

    // Mixed/Misc (3)
    LEVEL_25_LEGEND: {
        id: 'l5_level_25',
        title: '🌟 Level 25 Legend',
        description: 'Reach user level 25',
        icon: '🌟',
        category: 'level',
        level: 5,
        target: 25,
        xpReward: 2500,
        check: (user) => user.level.currentLevel >= 25,
    },
    ULTIMATE_MASTER: {
        id: 'l5_ultimate_master',
        title: '👑 Ultimate Master',
        description: 'Complete 500 total activities',
        icon: '👑',
        category: 'mastery',
        level: 5,
        target: 500,
        xpReward: 3000,
        check: (user) => (user.stats.totalDocuments + user.stats.totalQuizzes + user.stats.totalFlashcards) >= 500,
    },
    PERFECT_SCHOLAR: {
        id: 'l5_perfect_scholar',
        title: '💎 Perfect Scholar',
        description: 'Complete 1000 total activities',
        icon: '💎',
        category: 'mastery',
        level: 5,
        target: 1000,
        xpReward: 5000,
        check: (user) => (user.stats.totalDocuments + user.stats.totalQuizzes + user.stats.totalFlashcards) >= 1000,
    },
};

module.exports = {
    LEVEL_4_ACHIEVEMENTS,
    LEVEL_5_ACHIEVEMENTS,
};
